use_frameworks!

platform :ios, '9.0'

target 'TisComponent_Example' do
  pod 'TisComponent', :path => '../'

  target 'TisComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
